#!/bin/sh

usage() {
  echo "Usage: piprm <package1> [<package2> ...]"
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

for package in "$@"; do
    # 패키지의 의존성 확인
    dependencies=$(pip show "$package" | grep Requires | cut -d ':' -f 2 | tr -d ' ' | tr ',' ' ')

    # 패키지와 의존성 패키지 제거
    if [ -n "$dependencies" ]; then
        pip uninstall -y "$package" $dependencies
    else
        pip uninstall -y "$package"
    fi
done
